# Generated by Django 4.2 on 2024-08-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/non_avatar.png', null=True, upload_to='users/%Y', verbose_name='аватар'),
        ),
    ]
