# Generated by Django 4.2.15 on 2024-08-12 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
