# Generated by Django 4.2.15 on 2024-08-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='token_verify',
        ),
    ]
