# Generated by Django 4.2.15 on 2024-08-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Не указано', help_text='Укажите вашу страну', max_length=50, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Не указано', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Не указано', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='Не указано', help_text='Введите номер телефона', max_length=35, null=True, verbose_name='телефон'),
        ),
    ]
