# Generated by Django 4.2.15 on 2024-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_avatar_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='Не указано', max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
