# Generated by Django 4.2.15 on 2024-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Не указано', max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
