# Generated by Django 5.0.7 on 2024-08-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_active',
        ),
    ]
