# Generated by Django 5.0.7 on 2024-07-20 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_date_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='manufactured_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата создания категории'),
        ),
    ]
