# Generated by Django 5.0.7 on 2024-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_manufactured_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_create',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_edited',
            new_name='updated_at',
        ),
    ]
