# Generated by Django 5.0.7 on 2024-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_date_create_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_address', models.CharField(max_length=100, verbose_name='Адрес склада')),
                ('legal_address', models.CharField(max_length=100, verbose_name='Юридический адрес')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
