# Generated by Django 5.0.7 on 2024-07-21 13:21

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('D:/win/Store_Django/media/images'), verbose_name='Изображение'),
        ),
    ]
