# Generated by Django 5.0.7 on 2024-07-21 13:30

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default=pathlib.PureWindowsPath('D:/images/none.jpg'), null=True, upload_to=pathlib.PureWindowsPath('D:/images'), verbose_name='Изображение'),
        ),
    ]
