# Generated by Django 5.0.7 on 2024-07-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default='images/none.jpg', null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
