# Generated by Django 5.0.7 on 2024-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, default='catalog/none.jpg', null=True, upload_to='catalog/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
