# Generated by Django 5.0.7 on 2024-07-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
