# Generated by Django 4.2.15 on 2024-08-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_published_status', 'Can publish products')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
