# Generated by Django 4.2.15 on 2024-08-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_published', 'Can publish product'), ('set_description', 'Can edit description product'), ('set_category', 'Can change category product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
