# Generated by Django 4.2.15 on 2024-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
